### ISSUE TITLE
South Bay Events?

### ISSUE THREAD

**Issue by nesquena** [codepath/community-organizing#1]
Thread to discuss South Bay events. How do we find a way to make events happen in the South Bay? It all starts with venues. Post ideas for venues here or progress in contacting and confirming venues. 

One tip I received is to:

> Look into Hacker Dojo in Mountain View, it's a great space for holding events and recurring events..

Let's figure out venues and make these events happen! The [events format section](https://docs.google.com/a/thecodepath.com/document/d/1G6pES4kA8Hy7568FNEsPg6VgO7iSCozGk8CEMNuKYIo/edit#heading=h.lfeg7a9vil3x) contains all the information related to existing events we might want to run. We would probably start with one of the 2-hour evening events for about 30 people which introduces them to basics of Android development. Typically run one or two events per month. 

**Alumni Interested:** @vibhorB, @guptasachin25, @rutvijkumarshah, @rajab57, @richk, @madhurk, @sahil0984, @rajatb, @medha, @RaphaelTurtlePower

**Comment by nesquena** [comment]
@vibhorB @guptasachin25 @rutvijkumarshah and @rajab57 have all expressed interest in making south bay classes happen. Hope we can do this in the next few months. First step is locking down a venue for our first event.

**Comment by rajab57** [comment]
I can talk to a few people I know here in the South Bay.
Can I use this information from [CodePath Organizer Guide](https://docs.google.com/document/d/1G6pES4kA8Hy7568FNEsPg6VgO7iSCozGk8CEMNuKYIo/edit#) to chat with them ?

**Comment by nesquena** [comment]
@rajab57 yep! that'd be great.

**Comment by Michaelwellison** [comment]
@rajab57 @vibhorB @guptasachin25 @rutvijkumarshah 

My top pick is Box right now. You should the first event so that we have a date on the calendar.

We've been running meetups on Saturdays in SF but I don't think that's the best time. Mon-Wed evening would probably be more convenient for most people.

**Comment by nesquena** [comment]
New thread here for East Bay: https://github.com/thecodepath/community-organizing/issues/4 as well!

**Comment by nesquena** [comment]
Richa (@richk) has indicated interest in helping out as well

**Comment by nesquena** [comment]
Madhur (@madhurk) has also indicated interest in helping in the South Bay, adding him to the thread.

**Comment by guptasachin25** [comment]
Thanks @nesquena for starting this thread. Some of ideas me and nathan was discussing is creating a regular(most probably) meetup for codepath alumni in south bay. At the same time, start organizing small events for people who are interested in Android using same pattern @nesquena  is using. 

@richk @madhurk @rajab57 @rutvijkumarshah @vibhorB We can meet sometime tomorrow to discuss about possibilities while continuing working in parallel to decide about the venue. My email id is gupta.sachin25@gmail.com.

**Comment by madhurk** [comment]
I've been a member at Hacker Dojo before and its a great venue for organizing such events. I can find out the booking logistics there. 

Do we have topics in mind for the first event? If yes, please suggest them here and probable dates and we can do our first event pretty soon!

Madhur

**Comment by nesquena** [comment]
The [organizer document](https://docs.google.com/a/thecodepath.com/document/d/1G6pES4kA8Hy7568FNEsPg6VgO7iSCozGk8CEMNuKYIo/edit#heading=h.lfeg7a9vil3x) has all the details about existing event formats and how to get an event going. You all can also check out our existing [event curriculums here](https://github.com/thecodepath/community-organizing#curriculums) in detail here with schedules and all. As @guptasachin25 mentioned, would be cool to have a south bay alumni meetup as well for working on side projects, etc.

**Comment by nesquena** [comment]
Sahil (@sahil0984) has indicated interest in helping out as well! Glad that with our first Sunnyvale bootcamp completed, we now have enough alumni in the area to get these going.

**Comment by rajatb** [comment]
@rajatb I am interested in helping out teaching iOS.

**Comment by medha** [comment]
I would be interested in being part of South Bay events as well.

**Comment by RaphaelTurtlePower** [comment]
Definitely interested. Count me in. I'm excited to be a part of the South Bay initiative. please add @RaphaelTurtlePower!

**Comment by nesquena** [comment]
Great, StartX has agreed to host some of our events in South Bay. Connected them with @guptasachin25. Sachin, can you suggest a few dates and then have them confirm. It would be great if you could schedule a time to go down to the space and see if it's a good fit for our events as well.

**Comment by guptasachin25** [comment]
Thanks for introducing me to both Mozilla and StartX.

Sure. I will talk to both StartX and Mozilla and try to visit places this
week. Will update this thread with my findings.

Thanks
Sachin

---

Thanks
Sachin

On Sun, Aug 24, 2014 at 11:41 PM, Nathan Esquenazi <notifications@github.com

**Comment by nesquena** [comment]
Thanks to @guptasachin25, we now have our very first [south bay android event](http://www.meetup.com/Learning-Android-Development/events/206578642/) on 9/18 which is an evening session to help teach Android to people interested in getting started. You can review the [schedule here](https://docs.google.com/a/thecodepath.com/document/d/1VHMEwfVKeeq-sKyLK9h2TTQyx-w2YLiNxVld9XuIq9Q/edit) and [all other links](https://github.com/thecodepath/community-organizing/wiki) there.

The event is running people through building the basic todo app pre-work. We need more TAs and a brave instructor as well. If you can help, please [put your name in this sheet](https://docs.google.com/a/thecodepath.com/spreadsheets/d/1AHkcGmlhOmqL0yz1g9c7Pmi4uFhFj-vLqsngYRk923E/edit#gid=304081112). Thanks!

**Comment by rajatb** [comment]
Thanks Nathan,
How do we get started to get one training session for the iOS setup?

Rajat

**Comment by nesquena** [comment]
@rajatb it all starts with locating a venue, and then confirming a date with the venue. Once that happens, then we can post on meetup and start recruiting alumni to help out at the event.

**Comment by rajatb** [comment]
Can we use the same venue and see if its available of different dates?
Would that wor?

**Comment by nesquena** [comment]
Potentially yeah, @guptasachin25 has been the one communicating with venue, perhaps he can introduce you (maybe after our first event goes smoothly).

**Comment by rajatb** [comment]
Sounds good.
After the first event gets done. We can see if he can use the venue again
for iOS.

Thanks,
Rajat

**Comment by guptasachin25** [comment]
Hi Rajat,

That seems like an good option. Why don't you drop by in Android event and
see the space. We can have quick chat with sponsorer too.

Sachin

---

Thanks
Sachin

**Comment by rajatb** [comment]
Sounds good. I will be there.

thanks again,
Rajat Bhargava

**Comment by nesquena** [comment]
We have our [next south bay event](http://www.meetup.com/Learning-Android-Development/events/215473202/) scheduled on November 8th thanks to @rajab57! @vibhorB will be instructing as well. We need [2 more TAs](https://docs.google.com/a/thecodepath.com/spreadsheets/d/1AHkcGmlhOmqL0yz1g9c7Pmi4uFhFj-vLqsngYRk923E/edit#gid=1399799679) to help out. Sign up if you can help.  Also, any help promoting the event to more south bay people would be appreciated.
