### ISSUE TITLE
Content ready for review: Parse Guide to Common Issues

### ISSUE THREAD

**Issue by i0jupiter** [codepath/community-organizing#5]
https://github.com/thecodepath/community-organizing/wiki/Parse-Guide-to-Common-Scenarios

**Comment by nesquena** [comment]
This was also great, merged into a new [troubleshooting parse](https://github.com/thecodepath/android_guides/wiki/Troubleshooting-Common-Issues-with-Parse) standalone guide on cliffnotes! Thanks Shine!

**Comment by i0jupiter** [comment]
+1. Glad to have contributed.
